### ISSUE TITLE
problème de page blanche update version="doryphore"

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki#662]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug

**Description**

Test réalisé : 
 - Téléchargement et installation de yeswiki-cercopitheque-2021-01-29-1
 - Suivi du document : https://yeswiki.net/?DocumentationMiseAJour
 - Mise à jour du thème margot
 - Remplacement de {{update}} par {{update version="doryphore"}}
 - Clic sur Changer de version (Doryphore 2021-02-10-6)

```Fatal error: Uncaught Error: Class 'AutoUpdate\ViewUpdate' not found in \tools\autoupdate\app\Controller.php:44 Stack trace: #0 \tools\autoupdate\actions\update.php(22): AutoUpdate\Controller->run(Array, 'doryphore') #1 \includes\YesWiki.php(1437): include('\\c...') #2 \includes\YesWiki.php(1251): YesWiki\Wiki->IncludeBuffered('update.php', '<div class="ale...', Array, 'tools/toc/actio...') #3 \formatters\wakka.php(338): YesWiki\Wiki->Action('update') #4 [internal function]: WikiniFormatter->callback(Array) #5 \formatters\wakka.php(81): preg_replace_callback('/\%\%.*?\%\%|""...', Array, '{{nav links="Ge...') #6 \formatters\wakka.php(494): WikiniFormatter->format('{{nav links="Ge...') #7 \includes\YesWiki.php(1437): include('\\c...') #8 \includes\YesW in \tools\autoupdate\app\Controller.php on line 44 ```

**Comment by J9rem** [comment]
Faut-il mettre à jour l'autoupdate de cerco ?

**Comment by J9rem** [comment]
résolu par #677
