### ISSUE TITLE
[Cercopitheque] Demande récupération mot de passe : Error : il manque le dossier "vendor/PHPMailer"

### ISSUE THREAD

**Issue by fbredow** [YesWiki/yeswiki#669]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**
Bug / Bogue

**Description**
Sur un wiki fraîchement installé (cercopitheque du 29 janvier 2021) une erreur intervient si je demande à récupérer mon mot de passe. Il semble que le dossier Vendor ne soit plus présent dans l'archive d'installation. Il est bien présent si j'installe depuis la branche cercopitheque du dépot git.

**Additionnal informations / Informations complémentaires**
- version of YesWiki / version de YesWiki : yeswiki-cercopitheque-2021-01-29-1.zip  
- Message d'erreur : 
```
Warning: require(vendor/PHPMailer/src/Exception.php): Failed to open stream: No such file or directory in /var/www/html/includes/email.inc.php on line 5

Fatal error: Uncaught Error: Failed opening required 'vendor/PHPMailer/src/Exception.php' (include_path='.:/usr/local/lib/php') in /var/www/html/includes/email.inc.php:5 Stack trace: #0 /var/www/html/tools/login/libs/login.functions.php(57): require_once() #1 /var/www/html/tools/login/actions/lostpassword.php(34): sendPasswordEmail('WikiAdmin') #2 /var/www/html/includes/YesWiki.php(1437): include('/var/www/html/f...') #3 /var/www/html/includes/YesWiki.php(1251): YesWiki\Wiki->IncludeBuffered('lostpassword.ph...', '<div class="ale...', Array, 'tools/toc/actio...') #4 /var/www/html/formatters/wakka.php(338): YesWiki\Wiki->Action('lostpassword') #5 [internal function]: WikiniFormatter->callback(Array) #6 /var/www/html/formatters/wakka.php(81): preg_replace_callback('/\\%\\%.*?\\%\\%|""...', Array, '{{lostpassword}...') #7 /var/www/html/formatters/wakka.php(494): WikiniFormatter->format('{{lostpassword}...') #8 /var/www/html/includes/YesWiki.php(1437): include('/var/www/html/f...') #9 /var/www/html/includes/YesWiki.php(1371): YesWiki\Wiki->IncludeBuffered('wakka.php', '<i>Impossible d...', Array, 'tools/toc/forma...') #10 /var/www/html/handlers/page/show.php(95): YesWiki\Wiki->Format('{{lostpassword}...', 'wakka', 'MotDePassePerdu') #11 /var/www/html/includes/YesWiki.php(1437): include('/var/www/html/f...') #12 /var/www/html/includes/YesWiki.php(1364): YesWiki\Wiki->IncludeBuffered('page/show.php', '<i>M&eacute;tho...', '', 'tools/templates...') #13 /var/www/html/includes/YesWiki.php(2176): YesWiki\Wiki->Method('show') #14 /var/www/html/index.php(41): YesWiki\Wiki->Run('MotDePassePerdu', '') #15 {main} thrown in /var/www/html/includes/email.inc.php on line 5
```

**Comment by mrflos** [comment]
hello, normalement c'est corrigé par https://github.com/YesWiki/yeswiki/commit/ec6f584f8fbf38d48181155da1a0102f0f693df2
