### ISSUE TITLE
Erreur lors de l'upgrade vers `doryphore@2021-02-19-8`

### ISSUE THREAD

**Issue by thom4parisot** [YesWiki/yeswiki#679]
**Type of issue (keep only one) / Type de demande (ne garder qu'une ligne)**

Bug / Bogue

**Description**

Cette erreur s'est affichée lorsque j'ai cliqué sur le bouton "Mettre à jour" dans `?GererMisesAJour` :

```

Fatal error: Uncaught Error: Call to undefined method Twig\Environment::getTokenParser() in /home/oncletom/www_crest_comite21/vendor/twig/twig/src/Parser.php:153 Stack trace: #0 /home/oncletom/www_crest_comite21/vendor/twig/twig/src/Parser.php(84): Twig\Parser->subparse(NULL, false) #1 /home/oncletom/www_crest_comite21/vendor/twig/twig/src/Environment.php(479): Twig\Parser->parse(Object(Twig\TokenStream)) #2 /home/oncletom/www_crest_comite21/vendor/twig/twig/src/Environment.php(507): Twig\Environment->parse(Object(Twig\TokenStream)) #3 /home/oncletom/www_crest_comite21/vendor/twig/twig/src/Environment.php(348): Twig\Environment->compileSource(Object(Twig\Source)) #4 /home/oncletom/www_crest_comite21/vendor/twig/twig/src/Environment.php(309): Twig\Environment->loadTemplate('__TwigTemplate_...', '@autoupdate/upd...') #5 /home/oncletom/www_crest_comite21/vendor/twig/twig/src/Environment.php(277): Twig\Environment->load('@autoupdate/upd...') #6 /home/oncletom/www_crest_comite21/includes/services/TemplateEngine.php(121): Twig\ in /home/oncletom/www_crest_comite21/vendor/twig/twig/src/Parser.php on line 153
```

En actualisant la page, elle ne s'est pas affichée à nouveau, et le processus semble avoir fonctionné — en tous cas, la version détectée est `doryphore 2021-02-19-8`. Et je ne rencontre plus #638 dans cette version.

**Comment by J9rem** [comment]
Je clos cette issue car normalement, le souci ne devrait plus arriver avec la nouvelle méthode de mise à jour apportée par #685 qui permet de recharger le wiki en fin de mise à jour et éviter les problèmes dus  la modification des fichiers.
